apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: ${{ values.name }}
  janus-idp.io/tekton: ${{ values.name }}
  backstage.io/kubernetes-id: ${{ values.name }}
  backstage.io/kubernetes-namespace: ${{ values.namespace }}
  app.kubernetes.io/part-of: ${{ values.name }}
resources:
- application-dev.yaml
{%- if values.deployOnRemoteCluster %}
- ../components/${{ values.name }}/http/overlays/development/gitops-repository.yaml
- ../components/${{ values.name }}/http/overlays/development/source-repository.yaml
- ../components/${{ values.name }}/http/base/initialize-namespace.yaml
{%- endif %}
