{{- if .Values.rhoaiSelected }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-{{ .Values.appName }}
spec:  
  template:         
    metadata:
      name: dsp-clone-job-{{ .Values.appName }}
    spec:  
      serviceAccountName: {{ .Values.name }}-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset={{ .Values.name }}-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/{{ .Values.name }}-notebook -- git clone {{ .Values.srcRepoURL }}
      restartPolicy: Never
{{- end }}