{{- if .Values.rhoaiSelected }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-dsp-job
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}-imagestream-job-role
{{- end }}