apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - deployment-patch.yaml
resources:
  - ../../base
  {%- if values.deployOnRemoteCluster == nil or not(values.deployOnRemoteCluster) %}
  - gitops-repository.yaml
  - source-repository.yaml
  {%- endif %}