apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }} 
  name: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.appPort }}
    protocol: TCP
    targetPort: {{ .Values.appPort }}
  selector:
    app.kubernetes.io/instance: {{ .Values.name }} 
